name: lms_offline
description: "Thaheen, an offline learning app for students."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  easy_localization: ^3.0.8
  equatable: ^3.0.0
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.8
  flutter_svg: ^2.3.0
  get_it: ^9.3.0
  go_router: ^18.0.1
  pointycastle: ^4.0.0
  shared_preferences: ^2.5.5
  video_player: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/data/
    - assets/images/
    - assets/videos/anatomy/
    - assets/videos/physiology/
    - assets/videos/thaheen_offline_video_assets/
    - assets/fonts/licenses/

  fonts:
    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/CormorantGaramond-Regular.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-SemiBold.ttf
          weight: 600
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf

flutter_native_splash:
  color: "#1D5999"
  image: assets/splash/blank.png
  android_12:
    color: "#1D5999"
    image: assets/splash/blank.png
  web: false
